CREATE TABLE IF NOT EXISTS `BAA_REF_ENVIRONMENTS` (
  `REF_ID` int(11) NOT NULL,
  `REF_ENV_NAME` varchar(255) DEFAULT NULL,
  `REF_ENV_URL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`REF_ID`)
);